### ISSUE TITLE
computing election feature causes name error

### ISSUE THREAD

**Issue by itayzimet** [science-for-democracy/mapof-elections#1]
error :
`File "mapof-elections\src\mapof\elections\objects\ElectionExperiment.py", line 635, in compute_feature
    if feature_id in MAIN_GLOBAL_FEATUERS or feature_id in ELECTION_GLOBAL_FEATURES:
                     ^^^^^^^^^^^^^^^^^^^^
NameError: name 'MAIN_GLOBAL_FEATUERS' is not defined`

**Comment by itayzimet** [comment]
works for my specific case by just removing the whole if from said if block
i don't know the code-base good enough to know if that is a good long term solution

**Comment by szufix** [comment]
Thanks. I fixed this by adding appropriate imports.
